(dp1
S'output'
p2
S"<type 'exceptions.RuntimeError'> maximum recursion depth exceeded while calling a Python object"
p3
sS'layer'
p4
S'/home/bcr/projects/cursojulho12/web2py/applications/ecommerce/models/datamodel_application.py'
p5
sS'code'
p6
S'#coding: utf-8\n\n# definir objetos da app (Auth, Mail, Service)\n\nfrom gluon.tools import Auth, Mail\n\nauth = Auth(db, hmac_key=Auth.get_or_create_key())\n\n\n# CAPTCHA\n\n# from gluon.tools import Recaptcha\n# auth.settings.captcha = Recaptcha(request,\n#     \'PUBLIC_KEY\', \'PRIVATE_KEY\')\n\n# auth_user, auth_groups, auth_membership, auth_permission\n\n#auth.settings.extra_fields["auth_user"] = [CPF]\n\n# auth.settings.registration_requires_verification = False\n# auth.settings.registration_requires_approval = False\n# auth.settings.reset_password_requires_verification = True\n\nmail = Mail()\nmail.settings.sender = config.mail.sender\nmail.settings.server = config.mail.server\nmail.settings.login = config.mail.login\n\nauth.settings.mailer = mail\n\n# auth.settings.login_field = \'cpf\'\nauth.define_tables()\n\n# definir classes e funcoes da app\n# definir autenticacao\n# definir datamodel de autenticacao\n# definir emails de autenticacao\n\n# signature'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/restricted.py", line 205, in restricted\n    exec ccode in environment\n  File "/home/bcr/projects/cursojulho12/web2py/applications/ecommerce/models/datamodel_application.py", line 7, in <module>\n    auth = Auth(db, hmac_key=Auth.get_or_create_key())\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/tools.py", line 1127, in __init__\n    writable=False,readable=False))\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/dal.py", line 6628, in __init__\n    field.requires = sqlhtml_validators(field)\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/dal.py", line 5571, in sqlhtml_validators\n    requires.append(validators.IS_DATETIME())\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/validators.py", line 2167, in __init__\n    self.format = translate(format)\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/validators.py", line 64, in translate\n    return str(current.T(text))\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/languages.py", line 128, in __str__\n    return self.T.translate(self.m, self.s)\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/languages.py", line 281, in translate\n    is_gae = settings.global_settings.web2py_runtime_gae\n  File "/home/bcr/projects/cursojulho12/web2py/gluon/storage.py", line 58, in __getattr__\n    return dict.get(self, key, None)\nRuntimeError: maximum recursion depth exceeded while calling a Python object\n'
p11
s.